/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "key_led.h"
#include "MainDLG.h"
#include "common.h"
#include "my_png.h"
//#include "emwin_demo.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)


// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 22, 35, 190, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 23, 119, 190, 44, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 23, 203, 190, 39, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	uint32_t msg;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
	            FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            //FRAMEWIN_SetTextColor(hItem, 0x0000FFFF);
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(GUI_RED));
    FRAMEWIN_SetFont(hItem, GUI_FONT_24_ASCII);
	  FRAMEWIN_SetText(hItem,"Secure Wallet");
	
    FRAMEWIN_SetTitleHeight(hItem, 40);
	
	
    //
    // Initialization of 'Button'
    //

	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetSkinClassic(hItem); 
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
	//  BUTTON_SetBkColor(hItem, 0, GUI_BLUE);
    BUTTON_SetText(hItem, "Create wallet");
	
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
    BUTTON_SetText(hItem, "View wallet");
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		
		
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "Decrypt wallet");
		BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
		
	//		  BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
			{
				LED1_TOGGLE();
				int pngnum;
        pngnum=chkPngFile();
        if(pngnum>0)
				{					
				   WM_DeleteWindow(pMsg->hWin);
  			   msg	= MSG_CREATE_WALLET;
				}
				else
					msg	= MSG_CREATE_WALLET_NO;
			  (void)osMessagePut(myQueue01Handle, msg, 0U);			

	
				
				
			//	GUI_EndDialog(pMsg->hWin, 0);
			//	emwin_main();
				
			//	hItem = WM_GetDialogItem(pMsg->hWin, Id);
			//	BUTTON_SetTextColor(hItem, 0, GUI_RED);
				

			}
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					//	WM_DeleteWindow(pMsg->hWin);
				LED2_TOGGLE();
				{
					  msg	= MSG_VIEW_WALLET;
					 (void)osMessagePut(myQueue01Handle, msg, 0U);			
					
				}		
			

        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					//	WM_DeleteWindow(pMsg->hWin);
				LED3_TOGGLE();
				{
					  msg	= MSG_DECRYPT_WALLET;
					 (void)osMessagePut(myQueue01Handle, msg, 0U);			
					
				}		
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateMain(void) {
  WM_HWIN hWin;
 // hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, 0, 0, 0);
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
/**
 * @brief       emwin_main(emwin入口)
 * @param       无
 * @return      无
 */
void main_menu(void) 
{
    CreateMain();

 /*   while (1)
    {
        GUI_Delay(100);
    }*/
}

// USER END

/*************************** End of file ****************************/
